// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/schedule/new": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signin" | "/account/signup" | "/dashboard" | "/dashboard/schedule/new" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./dashboard/schedule/new/page.jsx": {
    id: "dashboard/schedule/new/page";
    page: "/dashboard/schedule/new";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};